_name_or_path:
    value: ../pretrained_models/bacteria_model
_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": eval/matthews_correlation
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/train_runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/recall
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/runtime
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/precision
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/total_flos
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/samples_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/steps_per_second
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": eval/confusion_matrix_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.8.20
            "5": 0.19.9
            "6": 4.29.2
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
        visualize:
            eval/confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: eval/confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
alibi_starting_size:
    value: 512
architectures:
    value:
        - BertForMaskedLM
attention_probs_dropout_prob:
    value: 0
auto_find_batch_size:
    value: false
auto_map:
    value:
        AutoConfig: configuration_bert.BertConfig
        AutoModel: bert_layers.BertModel
        AutoModelForMaskedLM: bert_layers.BertForMaskedLM
        AutoModelForSequenceClassification: bert_layers.BertForSequenceClassification
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
cache_dir:
    value: None
checkpointing:
    value: false
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: false
ddp_backend:
    value: None
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
decoder_start_token_id:
    value: null
deepspeed:
    value: None
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
epochs:
    value: 4
eval_accumulation_steps:
    value: None
eval_and_save_results:
    value: true
eval_batch_size:
    value: 16
eval_delay:
    value: 0
eval_steps:
    value: 1000
evaluation_strategy:
    value: steps
exponential_decay_length_penalty:
    value: null
find_unused_parameters:
    value: false
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: cuda_amp
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 768
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_eps:
    value: 1e-12
learning_rate:
    value: 3e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: info
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ../finetuned_models/per_species_models_v2/salmonella_enterica/runs/Sep09_15-46-24_a100-04
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 100
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 512
max_steps:
    value: -1
metric_for_best_model:
    value: f1
min_length:
    value: 0
model_max_length:
    value: 250
model_type:
    value: ""
mp_parameters:
    value: ""
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 12
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 4
optim:
    value: adamw_torch
optim_args:
    value: None
output_attentions:
    value: false
output_dir:
    value: ../finetuned_models/per_species_models_v2/salmonella_enterica
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: true
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 16
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
position_embedding_type:
    value: absolute
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: per_species_models_v2_salmonella_enterica
save_model:
    value: false
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 1000
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
sep_token_id:
    value: null
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: None
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torch_dtype:
    value: float32
torchdynamo:
    value: None
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 8
transformers_version:
    value: 4.29.2
type_vocab_size:
    value: 2
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 4096
warmup_ratio:
    value: 0
warmup_steps:
    value: 1000
weight_decay:
    value: 0.01
xpu_backend:
    value: None
