_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.9
            "6": 4.29.2
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
epochs:
    value: 4
learning_rate:
    value: 3e-05
per_device_train_batch_size:
    value: 8
